DROP DATABASE IF EXISTS valemobi;
CREATE DATABASE valemobi;
-- CREATE DATABASE cl58-valemobi; //CRIAÇÃO NO BD REMOTO//
USE valemobi;

DROP TABLE IF EXISTS negociacoes;
CREATE TABLE negociacoes (
  ID INT(255) UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  codMercadoria INT(10) UNSIGNED ZEROFILL NOT NULL,
  tipoMercadoria VARCHAR(75) NOT NULL,
  nome VARCHAR(75) NOT NULL,
  qtd MEDIUMINT UNSIGNED ZEROFILL NOT NULL,
  preco DECIMAL(10,2) UNSIGNED NOT NULL,
  tipoNegociacao  VARCHAR(75) NOT NULL
);
